INSERT INTO `aluno`(`id_aluno`, `user_id`, `nome_aluno`, `nascimento`, `sexo`, `telefone_aluno`, `email_aluno`, `nome_pai`, `telefone_pai`, `nome_mae`, `telefone_mae`, `nome_responsavel`, `telefone_resp`, `naturalidade`, `nacionalidade`, `rg`, `uf_rg`, `orgao_emissor`, `titulo_eleitor`, `zona`, `secao`, `certidao`, `uf_cert`, `cartorio_cert`, `modelo`, `numero`, `folha`, `livro`, `data_emissao_cert`, `municipio_cert`, `cpf`, `tipo_sanguineo`, `fazUsoMed`, `medicamentos`, `alergias`, `deficiencias`, `restric_alimentos`) VALUES (01,1,'ALUNO 01','1990-03-03','M',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `aluno`(`id_aluno`, `user_id`, `nome_aluno`, `nascimento`, `sexo`, `telefone_aluno`, `email_aluno`, `nome_pai`, `telefone_pai`, `nome_mae`, `telefone_mae`, `nome_responsavel`, `telefone_resp`, `naturalidade`, `nacionalidade`, `rg`, `uf_rg`, `orgao_emissor`, `titulo_eleitor`, `zona`, `secao`, `certidao`, `uf_cert`, `cartorio_cert`, `modelo`, `numero`, `folha`, `livro`, `data_emissao_cert`, `municipio_cert`, `cpf`, `tipo_sanguineo`, `fazUsoMed`, `medicamentos`, `alergias`, `deficiencias`, `restric_alimentos`) VALUES (02,1,'ALUNO 02','1990-03-03','M',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `aluno`(`id_aluno`, `user_id`, `nome_aluno`, `nascimento`, `sexo`, `telefone_aluno`, `email_aluno`, `nome_pai`, `telefone_pai`, `nome_mae`, `telefone_mae`, `nome_responsavel`, `telefone_resp`, `naturalidade`, `nacionalidade`, `rg`, `uf_rg`, `orgao_emissor`, `titulo_eleitor`, `zona`, `secao`, `certidao`, `uf_cert`, `cartorio_cert`, `modelo`, `numero`, `folha`, `livro`, `data_emissao_cert`, `municipio_cert`, `cpf`, `tipo_sanguineo`, `fazUsoMed`, `medicamentos`, `alergias`, `deficiencias`, `restric_alimentos`) VALUES (03,1,'ALUNO 03','1990-03-03','M',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `aluno`(`id_aluno`, `user_id`, `nome_aluno`, `nascimento`, `sexo`, `telefone_aluno`, `email_aluno`, `nome_pai`, `telefone_pai`, `nome_mae`, `telefone_mae`, `nome_responsavel`, `telefone_resp`, `naturalidade`, `nacionalidade`, `rg`, `uf_rg`, `orgao_emissor`, `titulo_eleitor`, `zona`, `secao`, `certidao`, `uf_cert`, `cartorio_cert`, `modelo`, `numero`, `folha`, `livro`, `data_emissao_cert`, `municipio_cert`, `cpf`, `tipo_sanguineo`, `fazUsoMed`, `medicamentos`, `alergias`, `deficiencias`, `restric_alimentos`) VALUES (04,1,'ALUNO 04','1990-03-03','M',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `aluno`(`id_aluno`, `user_id`, `nome_aluno`, `nascimento`, `sexo`, `telefone_aluno`, `email_aluno`, `nome_pai`, `telefone_pai`, `nome_mae`, `telefone_mae`, `nome_responsavel`, `telefone_resp`, `naturalidade`, `nacionalidade`, `rg`, `uf_rg`, `orgao_emissor`, `titulo_eleitor`, `zona`, `secao`, `certidao`, `uf_cert`, `cartorio_cert`, `modelo`, `numero`, `folha`, `livro`, `data_emissao_cert`, `municipio_cert`, `cpf`, `tipo_sanguineo`, `fazUsoMed`, `medicamentos`, `alergias`, `deficiencias`, `restric_alimentos`) VALUES (05,1,'ALUNO 05','1990-03-03','M',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `aluno`(`id_aluno`, `user_id`, `nome_aluno`, `nascimento`, `sexo`, `telefone_aluno`, `email_aluno`, `nome_pai`, `telefone_pai`, `nome_mae`, `telefone_mae`, `nome_responsavel`, `telefone_resp`, `naturalidade`, `nacionalidade`, `rg`, `uf_rg`, `orgao_emissor`, `titulo_eleitor`, `zona`, `secao`, `certidao`, `uf_cert`, `cartorio_cert`, `modelo`, `numero`, `folha`, `livro`, `data_emissao_cert`, `municipio_cert`, `cpf`, `tipo_sanguineo`, `fazUsoMed`, `medicamentos`, `alergias`, `deficiencias`, `restric_alimentos`) VALUES (06,1,'ALUNO 06','1990-03-03','M',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `aluno`(`id_aluno`, `user_id`, `nome_aluno`, `nascimento`, `sexo`, `telefone_aluno`, `email_aluno`, `nome_pai`, `telefone_pai`, `nome_mae`, `telefone_mae`, `nome_responsavel`, `telefone_resp`, `naturalidade`, `nacionalidade`, `rg`, `uf_rg`, `orgao_emissor`, `titulo_eleitor`, `zona`, `secao`, `certidao`, `uf_cert`, `cartorio_cert`, `modelo`, `numero`, `folha`, `livro`, `data_emissao_cert`, `municipio_cert`, `cpf`, `tipo_sanguineo`, `fazUsoMed`, `medicamentos`, `alergias`, `deficiencias`, `restric_alimentos`) VALUES (07,1,'ALUNO 07','1990-03-03','M',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `aluno`(`id_aluno`, `user_id`, `nome_aluno`, `nascimento`, `sexo`, `telefone_aluno`, `email_aluno`, `nome_pai`, `telefone_pai`, `nome_mae`, `telefone_mae`, `nome_responsavel`, `telefone_resp`, `naturalidade`, `nacionalidade`, `rg`, `uf_rg`, `orgao_emissor`, `titulo_eleitor`, `zona`, `secao`, `certidao`, `uf_cert`, `cartorio_cert`, `modelo`, `numero`, `folha`, `livro`, `data_emissao_cert`, `municipio_cert`, `cpf`, `tipo_sanguineo`, `fazUsoMed`, `medicamentos`, `alergias`, `deficiencias`, `restric_alimentos`) VALUES (08,1,'ALUNO 08','1990-03-03','M',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `aluno`(`id_aluno`, `user_id`, `nome_aluno`, `nascimento`, `sexo`, `telefone_aluno`, `email_aluno`, `nome_pai`, `telefone_pai`, `nome_mae`, `telefone_mae`, `nome_responsavel`, `telefone_resp`, `naturalidade`, `nacionalidade`, `rg`, `uf_rg`, `orgao_emissor`, `titulo_eleitor`, `zona`, `secao`, `certidao`, `uf_cert`, `cartorio_cert`, `modelo`, `numero`, `folha`, `livro`, `data_emissao_cert`, `municipio_cert`, `cpf`, `tipo_sanguineo`, `fazUsoMed`, `medicamentos`, `alergias`, `deficiencias`, `restric_alimentos`) VALUES (09,1,'ALUNO 09','1990-03-03','M',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `aluno`(`id_aluno`, `user_id`, `nome_aluno`, `nascimento`, `sexo`, `telefone_aluno`, `email_aluno`, `nome_pai`, `telefone_pai`, `nome_mae`, `telefone_mae`, `nome_responsavel`, `telefone_resp`, `naturalidade`, `nacionalidade`, `rg`, `uf_rg`, `orgao_emissor`, `titulo_eleitor`, `zona`, `secao`, `certidao`, `uf_cert`, `cartorio_cert`, `modelo`, `numero`, `folha`, `livro`, `data_emissao_cert`, `municipio_cert`, `cpf`, `tipo_sanguineo`, `fazUsoMed`, `medicamentos`, `alergias`, `deficiencias`, `restric_alimentos`) VALUES (10,1,'ALUNO 10','1990-03-03','M',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `aluno`(`id_aluno`, `user_id`, `nome_aluno`, `nascimento`, `sexo`, `telefone_aluno`, `email_aluno`, `nome_pai`, `telefone_pai`, `nome_mae`, `telefone_mae`, `nome_responsavel`, `telefone_resp`, `naturalidade`, `nacionalidade`, `rg`, `uf_rg`, `orgao_emissor`, `titulo_eleitor`, `zona`, `secao`, `certidao`, `uf_cert`, `cartorio_cert`, `modelo`, `numero`, `folha`, `livro`, `data_emissao_cert`, `municipio_cert`, `cpf`, `tipo_sanguineo`, `fazUsoMed`, `medicamentos`, `alergias`, `deficiencias`, `restric_alimentos`) VALUES (11,1,'ALUNO 11','1990-03-03','M',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `aluno`(`id_aluno`, `user_id`, `nome_aluno`, `nascimento`, `sexo`, `telefone_aluno`, `email_aluno`, `nome_pai`, `telefone_pai`, `nome_mae`, `telefone_mae`, `nome_responsavel`, `telefone_resp`, `naturalidade`, `nacionalidade`, `rg`, `uf_rg`, `orgao_emissor`, `titulo_eleitor`, `zona`, `secao`, `certidao`, `uf_cert`, `cartorio_cert`, `modelo`, `numero`, `folha`, `livro`, `data_emissao_cert`, `municipio_cert`, `cpf`, `tipo_sanguineo`, `fazUsoMed`, `medicamentos`, `alergias`, `deficiencias`, `restric_alimentos`) VALUES (12,1,'ALUNO 12','1990-03-03','M',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `aluno`(`id_aluno`, `user_id`, `nome_aluno`, `nascimento`, `sexo`, `telefone_aluno`, `email_aluno`, `nome_pai`, `telefone_pai`, `nome_mae`, `telefone_mae`, `nome_responsavel`, `telefone_resp`, `naturalidade`, `nacionalidade`, `rg`, `uf_rg`, `orgao_emissor`, `titulo_eleitor`, `zona`, `secao`, `certidao`, `uf_cert`, `cartorio_cert`, `modelo`, `numero`, `folha`, `livro`, `data_emissao_cert`, `municipio_cert`, `cpf`, `tipo_sanguineo`, `fazUsoMed`, `medicamentos`, `alergias`, `deficiencias`, `restric_alimentos`) VALUES (13,1,'ALUNO 13','1990-03-03','M',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `aluno`(`id_aluno`, `user_id`, `nome_aluno`, `nascimento`, `sexo`, `telefone_aluno`, `email_aluno`, `nome_pai`, `telefone_pai`, `nome_mae`, `telefone_mae`, `nome_responsavel`, `telefone_resp`, `naturalidade`, `nacionalidade`, `rg`, `uf_rg`, `orgao_emissor`, `titulo_eleitor`, `zona`, `secao`, `certidao`, `uf_cert`, `cartorio_cert`, `modelo`, `numero`, `folha`, `livro`, `data_emissao_cert`, `municipio_cert`, `cpf`, `tipo_sanguineo`, `fazUsoMed`, `medicamentos`, `alergias`, `deficiencias`, `restric_alimentos`) VALUES (14,1,'ALUNO 14','1990-03-03','M',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `aluno`(`id_aluno`, `user_id`, `nome_aluno`, `nascimento`, `sexo`, `telefone_aluno`, `email_aluno`, `nome_pai`, `telefone_pai`, `nome_mae`, `telefone_mae`, `nome_responsavel`, `telefone_resp`, `naturalidade`, `nacionalidade`, `rg`, `uf_rg`, `orgao_emissor`, `titulo_eleitor`, `zona`, `secao`, `certidao`, `uf_cert`, `cartorio_cert`, `modelo`, `numero`, `folha`, `livro`, `data_emissao_cert`, `municipio_cert`, `cpf`, `tipo_sanguineo`, `fazUsoMed`, `medicamentos`, `alergias`, `deficiencias`, `restric_alimentos`) VALUES (15,1,'ALUNO 15','1990-03-03','M',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `aluno`(`id_aluno`, `user_id`, `nome_aluno`, `nascimento`, `sexo`, `telefone_aluno`, `email_aluno`, `nome_pai`, `telefone_pai`, `nome_mae`, `telefone_mae`, `nome_responsavel`, `telefone_resp`, `naturalidade`, `nacionalidade`, `rg`, `uf_rg`, `orgao_emissor`, `titulo_eleitor`, `zona`, `secao`, `certidao`, `uf_cert`, `cartorio_cert`, `modelo`, `numero`, `folha`, `livro`, `data_emissao_cert`, `municipio_cert`, `cpf`, `tipo_sanguineo`, `fazUsoMed`, `medicamentos`, `alergias`, `deficiencias`, `restric_alimentos`) VALUES (16,1,'ALUNO 16','1990-03-03','M',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `aluno`(`id_aluno`, `user_id`, `nome_aluno`, `nascimento`, `sexo`, `telefone_aluno`, `email_aluno`, `nome_pai`, `telefone_pai`, `nome_mae`, `telefone_mae`, `nome_responsavel`, `telefone_resp`, `naturalidade`, `nacionalidade`, `rg`, `uf_rg`, `orgao_emissor`, `titulo_eleitor`, `zona`, `secao`, `certidao`, `uf_cert`, `cartorio_cert`, `modelo`, `numero`, `folha`, `livro`, `data_emissao_cert`, `municipio_cert`, `cpf`, `tipo_sanguineo`, `fazUsoMed`, `medicamentos`, `alergias`, `deficiencias`, `restric_alimentos`) VALUES (17,1,'ALUNO 17','1990-03-03','M',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `aluno`(`id_aluno`, `user_id`, `nome_aluno`, `nascimento`, `sexo`, `telefone_aluno`, `email_aluno`, `nome_pai`, `telefone_pai`, `nome_mae`, `telefone_mae`, `nome_responsavel`, `telefone_resp`, `naturalidade`, `nacionalidade`, `rg`, `uf_rg`, `orgao_emissor`, `titulo_eleitor`, `zona`, `secao`, `certidao`, `uf_cert`, `cartorio_cert`, `modelo`, `numero`, `folha`, `livro`, `data_emissao_cert`, `municipio_cert`, `cpf`, `tipo_sanguineo`, `fazUsoMed`, `medicamentos`, `alergias`, `deficiencias`, `restric_alimentos`) VALUES (18,1,'ALUNO 18','1990-03-03','M',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `aluno`(`id_aluno`, `user_id`, `nome_aluno`, `nascimento`, `sexo`, `telefone_aluno`, `email_aluno`, `nome_pai`, `telefone_pai`, `nome_mae`, `telefone_mae`, `nome_responsavel`, `telefone_resp`, `naturalidade`, `nacionalidade`, `rg`, `uf_rg`, `orgao_emissor`, `titulo_eleitor`, `zona`, `secao`, `certidao`, `uf_cert`, `cartorio_cert`, `modelo`, `numero`, `folha`, `livro`, `data_emissao_cert`, `municipio_cert`, `cpf`, `tipo_sanguineo`, `fazUsoMed`, `medicamentos`, `alergias`, `deficiencias`, `restric_alimentos`) VALUES (19,1,'ALUNO 19','1990-03-03','M',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `aluno`(`id_aluno`, `user_id`, `nome_aluno`, `nascimento`, `sexo`, `telefone_aluno`, `email_aluno`, `nome_pai`, `telefone_pai`, `nome_mae`, `telefone_mae`, `nome_responsavel`, `telefone_resp`, `naturalidade`, `nacionalidade`, `rg`, `uf_rg`, `orgao_emissor`, `titulo_eleitor`, `zona`, `secao`, `certidao`, `uf_cert`, `cartorio_cert`, `modelo`, `numero`, `folha`, `livro`, `data_emissao_cert`, `municipio_cert`, `cpf`, `tipo_sanguineo`, `fazUsoMed`, `medicamentos`, `alergias`, `deficiencias`, `restric_alimentos`) VALUES (20,1,'ALUNO 20','1990-03-03','M',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `aluno`(`id_aluno`, `user_id`, `nome_aluno`, `nascimento`, `sexo`, `telefone_aluno`, `email_aluno`, `nome_pai`, `telefone_pai`, `nome_mae`, `telefone_mae`, `nome_responsavel`, `telefone_resp`, `naturalidade`, `nacionalidade`, `rg`, `uf_rg`, `orgao_emissor`, `titulo_eleitor`, `zona`, `secao`, `certidao`, `uf_cert`, `cartorio_cert`, `modelo`, `numero`, `folha`, `livro`, `data_emissao_cert`, `municipio_cert`, `cpf`, `tipo_sanguineo`, `fazUsoMed`, `medicamentos`, `alergias`, `deficiencias`, `restric_alimentos`) VALUES (21,1,'ALUNO 21','1990-03-03','M',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `aluno`(`id_aluno`, `user_id`, `nome_aluno`, `nascimento`, `sexo`, `telefone_aluno`, `email_aluno`, `nome_pai`, `telefone_pai`, `nome_mae`, `telefone_mae`, `nome_responsavel`, `telefone_resp`, `naturalidade`, `nacionalidade`, `rg`, `uf_rg`, `orgao_emissor`, `titulo_eleitor`, `zona`, `secao`, `certidao`, `uf_cert`, `cartorio_cert`, `modelo`, `numero`, `folha`, `livro`, `data_emissao_cert`, `municipio_cert`, `cpf`, `tipo_sanguineo`, `fazUsoMed`, `medicamentos`, `alergias`, `deficiencias`, `restric_alimentos`) VALUES (22,1,'ALUNO 22','1990-03-03','M',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `aluno`(`id_aluno`, `user_id`, `nome_aluno`, `nascimento`, `sexo`, `telefone_aluno`, `email_aluno`, `nome_pai`, `telefone_pai`, `nome_mae`, `telefone_mae`, `nome_responsavel`, `telefone_resp`, `naturalidade`, `nacionalidade`, `rg`, `uf_rg`, `orgao_emissor`, `titulo_eleitor`, `zona`, `secao`, `certidao`, `uf_cert`, `cartorio_cert`, `modelo`, `numero`, `folha`, `livro`, `data_emissao_cert`, `municipio_cert`, `cpf`, `tipo_sanguineo`, `fazUsoMed`, `medicamentos`, `alergias`, `deficiencias`, `restric_alimentos`) VALUES (23,1,'ALUNO 23','1990-03-03','M',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `aluno`(`id_aluno`, `user_id`, `nome_aluno`, `nascimento`, `sexo`, `telefone_aluno`, `email_aluno`, `nome_pai`, `telefone_pai`, `nome_mae`, `telefone_mae`, `nome_responsavel`, `telefone_resp`, `naturalidade`, `nacionalidade`, `rg`, `uf_rg`, `orgao_emissor`, `titulo_eleitor`, `zona`, `secao`, `certidao`, `uf_cert`, `cartorio_cert`, `modelo`, `numero`, `folha`, `livro`, `data_emissao_cert`, `municipio_cert`, `cpf`, `tipo_sanguineo`, `fazUsoMed`, `medicamentos`, `alergias`, `deficiencias`, `restric_alimentos`) VALUES (24,1,'ALUNO 24','1990-03-03','M',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `aluno`(`id_aluno`, `user_id`, `nome_aluno`, `nascimento`, `sexo`, `telefone_aluno`, `email_aluno`, `nome_pai`, `telefone_pai`, `nome_mae`, `telefone_mae`, `nome_responsavel`, `telefone_resp`, `naturalidade`, `nacionalidade`, `rg`, `uf_rg`, `orgao_emissor`, `titulo_eleitor`, `zona`, `secao`, `certidao`, `uf_cert`, `cartorio_cert`, `modelo`, `numero`, `folha`, `livro`, `data_emissao_cert`, `municipio_cert`, `cpf`, `tipo_sanguineo`, `fazUsoMed`, `medicamentos`, `alergias`, `deficiencias`, `restric_alimentos`) VALUES (25,1,'ALUNO 25','1990-03-03','M',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `aluno`(`id_aluno`, `user_id`, `nome_aluno`, `nascimento`, `sexo`, `telefone_aluno`, `email_aluno`, `nome_pai`, `telefone_pai`, `nome_mae`, `telefone_mae`, `nome_responsavel`, `telefone_resp`, `naturalidade`, `nacionalidade`, `rg`, `uf_rg`, `orgao_emissor`, `titulo_eleitor`, `zona`, `secao`, `certidao`, `uf_cert`, `cartorio_cert`, `modelo`, `numero`, `folha`, `livro`, `data_emissao_cert`, `municipio_cert`, `cpf`, `tipo_sanguineo`, `fazUsoMed`, `medicamentos`, `alergias`, `deficiencias`, `restric_alimentos`) VALUES (26,1,'ALUNO 26','1990-03-03','M',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `aluno`(`id_aluno`, `user_id`, `nome_aluno`, `nascimento`, `sexo`, `telefone_aluno`, `email_aluno`, `nome_pai`, `telefone_pai`, `nome_mae`, `telefone_mae`, `nome_responsavel`, `telefone_resp`, `naturalidade`, `nacionalidade`, `rg`, `uf_rg`, `orgao_emissor`, `titulo_eleitor`, `zona`, `secao`, `certidao`, `uf_cert`, `cartorio_cert`, `modelo`, `numero`, `folha`, `livro`, `data_emissao_cert`, `municipio_cert`, `cpf`, `tipo_sanguineo`, `fazUsoMed`, `medicamentos`, `alergias`, `deficiencias`, `restric_alimentos`) VALUES (27,1,'ALUNO 27','1990-03-03','M',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `aluno`(`id_aluno`, `user_id`, `nome_aluno`, `nascimento`, `sexo`, `telefone_aluno`, `email_aluno`, `nome_pai`, `telefone_pai`, `nome_mae`, `telefone_mae`, `nome_responsavel`, `telefone_resp`, `naturalidade`, `nacionalidade`, `rg`, `uf_rg`, `orgao_emissor`, `titulo_eleitor`, `zona`, `secao`, `certidao`, `uf_cert`, `cartorio_cert`, `modelo`, `numero`, `folha`, `livro`, `data_emissao_cert`, `municipio_cert`, `cpf`, `tipo_sanguineo`, `fazUsoMed`, `medicamentos`, `alergias`, `deficiencias`, `restric_alimentos`) VALUES (28,1,'ALUNO 28','1990-03-03','M',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `aluno`(`id_aluno`, `user_id`, `nome_aluno`, `nascimento`, `sexo`, `telefone_aluno`, `email_aluno`, `nome_pai`, `telefone_pai`, `nome_mae`, `telefone_mae`, `nome_responsavel`, `telefone_resp`, `naturalidade`, `nacionalidade`, `rg`, `uf_rg`, `orgao_emissor`, `titulo_eleitor`, `zona`, `secao`, `certidao`, `uf_cert`, `cartorio_cert`, `modelo`, `numero`, `folha`, `livro`, `data_emissao_cert`, `municipio_cert`, `cpf`, `tipo_sanguineo`, `fazUsoMed`, `medicamentos`, `alergias`, `deficiencias`, `restric_alimentos`) VALUES (29,1,'ALUNO 29','1990-03-03','M',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `aluno`(`id_aluno`, `user_id`, `nome_aluno`, `nascimento`, `sexo`, `telefone_aluno`, `email_aluno`, `nome_pai`, `telefone_pai`, `nome_mae`, `telefone_mae`, `nome_responsavel`, `telefone_resp`, `naturalidade`, `nacionalidade`, `rg`, `uf_rg`, `orgao_emissor`, `titulo_eleitor`, `zona`, `secao`, `certidao`, `uf_cert`, `cartorio_cert`, `modelo`, `numero`, `folha`, `livro`, `data_emissao_cert`, `municipio_cert`, `cpf`, `tipo_sanguineo`, `fazUsoMed`, `medicamentos`, `alergias`, `deficiencias`, `restric_alimentos`) VALUES (30,1,'ALUNO 30','1990-03-03','M',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `aluno`(`id_aluno`, `user_id`, `nome_aluno`, `nascimento`, `sexo`, `telefone_aluno`, `email_aluno`, `nome_pai`, `telefone_pai`, `nome_mae`, `telefone_mae`, `nome_responsavel`, `telefone_resp`, `naturalidade`, `nacionalidade`, `rg`, `uf_rg`, `orgao_emissor`, `titulo_eleitor`, `zona`, `secao`, `certidao`, `uf_cert`, `cartorio_cert`, `modelo`, `numero`, `folha`, `livro`, `data_emissao_cert`, `municipio_cert`, `cpf`, `tipo_sanguineo`, `fazUsoMed`, `medicamentos`, `alergias`, `deficiencias`, `restric_alimentos`) VALUES (31,1,'ALUNO 31','1990-03-03','M',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `aluno`(`id_aluno`, `user_id`, `nome_aluno`, `nascimento`, `sexo`, `telefone_aluno`, `email_aluno`, `nome_pai`, `telefone_pai`, `nome_mae`, `telefone_mae`, `nome_responsavel`, `telefone_resp`, `naturalidade`, `nacionalidade`, `rg`, `uf_rg`, `orgao_emissor`, `titulo_eleitor`, `zona`, `secao`, `certidao`, `uf_cert`, `cartorio_cert`, `modelo`, `numero`, `folha`, `livro`, `data_emissao_cert`, `municipio_cert`, `cpf`, `tipo_sanguineo`, `fazUsoMed`, `medicamentos`, `alergias`, `deficiencias`, `restric_alimentos`) VALUES (32,1,'ALUNO 32','1990-03-03','M',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `aluno`(`id_aluno`, `user_id`, `nome_aluno`, `nascimento`, `sexo`, `telefone_aluno`, `email_aluno`, `nome_pai`, `telefone_pai`, `nome_mae`, `telefone_mae`, `nome_responsavel`, `telefone_resp`, `naturalidade`, `nacionalidade`, `rg`, `uf_rg`, `orgao_emissor`, `titulo_eleitor`, `zona`, `secao`, `certidao`, `uf_cert`, `cartorio_cert`, `modelo`, `numero`, `folha`, `livro`, `data_emissao_cert`, `municipio_cert`, `cpf`, `tipo_sanguineo`, `fazUsoMed`, `medicamentos`, `alergias`, `deficiencias`, `restric_alimentos`) VALUES (33,1,'ALUNO 33','1990-03-03','M',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `aluno`(`id_aluno`, `user_id`, `nome_aluno`, `nascimento`, `sexo`, `telefone_aluno`, `email_aluno`, `nome_pai`, `telefone_pai`, `nome_mae`, `telefone_mae`, `nome_responsavel`, `telefone_resp`, `naturalidade`, `nacionalidade`, `rg`, `uf_rg`, `orgao_emissor`, `titulo_eleitor`, `zona`, `secao`, `certidao`, `uf_cert`, `cartorio_cert`, `modelo`, `numero`, `folha`, `livro`, `data_emissao_cert`, `municipio_cert`, `cpf`, `tipo_sanguineo`, `fazUsoMed`, `medicamentos`, `alergias`, `deficiencias`, `restric_alimentos`) VALUES (34,1,'ALUNO 34','1990-03-03','M',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `aluno`(`id_aluno`, `user_id`, `nome_aluno`, `nascimento`, `sexo`, `telefone_aluno`, `email_aluno`, `nome_pai`, `telefone_pai`, `nome_mae`, `telefone_mae`, `nome_responsavel`, `telefone_resp`, `naturalidade`, `nacionalidade`, `rg`, `uf_rg`, `orgao_emissor`, `titulo_eleitor`, `zona`, `secao`, `certidao`, `uf_cert`, `cartorio_cert`, `modelo`, `numero`, `folha`, `livro`, `data_emissao_cert`, `municipio_cert`, `cpf`, `tipo_sanguineo`, `fazUsoMed`, `medicamentos`, `alergias`, `deficiencias`, `restric_alimentos`) VALUES (35,1,'ALUNO 35','1990-03-03','M',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `aluno`(`id_aluno`, `user_id`, `nome_aluno`, `nascimento`, `sexo`, `telefone_aluno`, `email_aluno`, `nome_pai`, `telefone_pai`, `nome_mae`, `telefone_mae`, `nome_responsavel`, `telefone_resp`, `naturalidade`, `nacionalidade`, `rg`, `uf_rg`, `orgao_emissor`, `titulo_eleitor`, `zona`, `secao`, `certidao`, `uf_cert`, `cartorio_cert`, `modelo`, `numero`, `folha`, `livro`, `data_emissao_cert`, `municipio_cert`, `cpf`, `tipo_sanguineo`, `fazUsoMed`, `medicamentos`, `alergias`, `deficiencias`, `restric_alimentos`) VALUES (36,1,'ALUNO 36','1990-03-03','M',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `aluno`(`id_aluno`, `user_id`, `nome_aluno`, `nascimento`, `sexo`, `telefone_aluno`, `email_aluno`, `nome_pai`, `telefone_pai`, `nome_mae`, `telefone_mae`, `nome_responsavel`, `telefone_resp`, `naturalidade`, `nacionalidade`, `rg`, `uf_rg`, `orgao_emissor`, `titulo_eleitor`, `zona`, `secao`, `certidao`, `uf_cert`, `cartorio_cert`, `modelo`, `numero`, `folha`, `livro`, `data_emissao_cert`, `municipio_cert`, `cpf`, `tipo_sanguineo`, `fazUsoMed`, `medicamentos`, `alergias`, `deficiencias`, `restric_alimentos`) VALUES (37,1,'ALUNO 37','1990-03-03','M',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `aluno`(`id_aluno`, `user_id`, `nome_aluno`, `nascimento`, `sexo`, `telefone_aluno`, `email_aluno`, `nome_pai`, `telefone_pai`, `nome_mae`, `telefone_mae`, `nome_responsavel`, `telefone_resp`, `naturalidade`, `nacionalidade`, `rg`, `uf_rg`, `orgao_emissor`, `titulo_eleitor`, `zona`, `secao`, `certidao`, `uf_cert`, `cartorio_cert`, `modelo`, `numero`, `folha`, `livro`, `data_emissao_cert`, `municipio_cert`, `cpf`, `tipo_sanguineo`, `fazUsoMed`, `medicamentos`, `alergias`, `deficiencias`, `restric_alimentos`) VALUES (38,1,'ALUNO 38','1990-03-03','M',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `aluno`(`id_aluno`, `user_id`, `nome_aluno`, `nascimento`, `sexo`, `telefone_aluno`, `email_aluno`, `nome_pai`, `telefone_pai`, `nome_mae`, `telefone_mae`, `nome_responsavel`, `telefone_resp`, `naturalidade`, `nacionalidade`, `rg`, `uf_rg`, `orgao_emissor`, `titulo_eleitor`, `zona`, `secao`, `certidao`, `uf_cert`, `cartorio_cert`, `modelo`, `numero`, `folha`, `livro`, `data_emissao_cert`, `municipio_cert`, `cpf`, `tipo_sanguineo`, `fazUsoMed`, `medicamentos`, `alergias`, `deficiencias`, `restric_alimentos`) VALUES (39,1,'ALUNO 39','1990-03-03','M',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `aluno`(`id_aluno`, `user_id`, `nome_aluno`, `nascimento`, `sexo`, `telefone_aluno`, `email_aluno`, `nome_pai`, `telefone_pai`, `nome_mae`, `telefone_mae`, `nome_responsavel`, `telefone_resp`, `naturalidade`, `nacionalidade`, `rg`, `uf_rg`, `orgao_emissor`, `titulo_eleitor`, `zona`, `secao`, `certidao`, `uf_cert`, `cartorio_cert`, `modelo`, `numero`, `folha`, `livro`, `data_emissao_cert`, `municipio_cert`, `cpf`, `tipo_sanguineo`, `fazUsoMed`, `medicamentos`, `alergias`, `deficiencias`, `restric_alimentos`) VALUES (40,1,'ALUNO 40','1990-03-03','M',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `aluno`(`id_aluno`, `user_id`, `nome_aluno`, `nascimento`, `sexo`, `telefone_aluno`, `email_aluno`, `nome_pai`, `telefone_pai`, `nome_mae`, `telefone_mae`, `nome_responsavel`, `telefone_resp`, `naturalidade`, `nacionalidade`, `rg`, `uf_rg`, `orgao_emissor`, `titulo_eleitor`, `zona`, `secao`, `certidao`, `uf_cert`, `cartorio_cert`, `modelo`, `numero`, `folha`, `livro`, `data_emissao_cert`, `municipio_cert`, `cpf`, `tipo_sanguineo`, `fazUsoMed`, `medicamentos`, `alergias`, `deficiencias`, `restric_alimentos`) VALUES (41,1,'ALUNO 41','1990-03-03','M',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `aluno`(`id_aluno`, `user_id`, `nome_aluno`, `nascimento`, `sexo`, `telefone_aluno`, `email_aluno`, `nome_pai`, `telefone_pai`, `nome_mae`, `telefone_mae`, `nome_responsavel`, `telefone_resp`, `naturalidade`, `nacionalidade`, `rg`, `uf_rg`, `orgao_emissor`, `titulo_eleitor`, `zona`, `secao`, `certidao`, `uf_cert`, `cartorio_cert`, `modelo`, `numero`, `folha`, `livro`, `data_emissao_cert`, `municipio_cert`, `cpf`, `tipo_sanguineo`, `fazUsoMed`, `medicamentos`, `alergias`, `deficiencias`, `restric_alimentos`) VALUES (42,1,'ALUNO 42','1990-03-03','M',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `aluno`(`id_aluno`, `user_id`, `nome_aluno`, `nascimento`, `sexo`, `telefone_aluno`, `email_aluno`, `nome_pai`, `telefone_pai`, `nome_mae`, `telefone_mae`, `nome_responsavel`, `telefone_resp`, `naturalidade`, `nacionalidade`, `rg`, `uf_rg`, `orgao_emissor`, `titulo_eleitor`, `zona`, `secao`, `certidao`, `uf_cert`, `cartorio_cert`, `modelo`, `numero`, `folha`, `livro`, `data_emissao_cert`, `municipio_cert`, `cpf`, `tipo_sanguineo`, `fazUsoMed`, `medicamentos`, `alergias`, `deficiencias`, `restric_alimentos`) VALUES (43,1,'ALUNO 43','1990-03-03','M',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `aluno`(`id_aluno`, `user_id`, `nome_aluno`, `nascimento`, `sexo`, `telefone_aluno`, `email_aluno`, `nome_pai`, `telefone_pai`, `nome_mae`, `telefone_mae`, `nome_responsavel`, `telefone_resp`, `naturalidade`, `nacionalidade`, `rg`, `uf_rg`, `orgao_emissor`, `titulo_eleitor`, `zona`, `secao`, `certidao`, `uf_cert`, `cartorio_cert`, `modelo`, `numero`, `folha`, `livro`, `data_emissao_cert`, `municipio_cert`, `cpf`, `tipo_sanguineo`, `fazUsoMed`, `medicamentos`, `alergias`, `deficiencias`, `restric_alimentos`) VALUES (44,1,'ALUNO 44','1990-03-03','M',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `aluno`(`id_aluno`, `user_id`, `nome_aluno`, `nascimento`, `sexo`, `telefone_aluno`, `email_aluno`, `nome_pai`, `telefone_pai`, `nome_mae`, `telefone_mae`, `nome_responsavel`, `telefone_resp`, `naturalidade`, `nacionalidade`, `rg`, `uf_rg`, `orgao_emissor`, `titulo_eleitor`, `zona`, `secao`, `certidao`, `uf_cert`, `cartorio_cert`, `modelo`, `numero`, `folha`, `livro`, `data_emissao_cert`, `municipio_cert`, `cpf`, `tipo_sanguineo`, `fazUsoMed`, `medicamentos`, `alergias`, `deficiencias`, `restric_alimentos`) VALUES (45,1,'ALUNO 45','1990-03-03','M',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `aluno`(`id_aluno`, `user_id`, `nome_aluno`, `nascimento`, `sexo`, `telefone_aluno`, `email_aluno`, `nome_pai`, `telefone_pai`, `nome_mae`, `telefone_mae`, `nome_responsavel`, `telefone_resp`, `naturalidade`, `nacionalidade`, `rg`, `uf_rg`, `orgao_emissor`, `titulo_eleitor`, `zona`, `secao`, `certidao`, `uf_cert`, `cartorio_cert`, `modelo`, `numero`, `folha`, `livro`, `data_emissao_cert`, `municipio_cert`, `cpf`, `tipo_sanguineo`, `fazUsoMed`, `medicamentos`, `alergias`, `deficiencias`, `restric_alimentos`) VALUES (46,1,'ALUNO 46','1990-03-03','M',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `aluno`(`id_aluno`, `user_id`, `nome_aluno`, `nascimento`, `sexo`, `telefone_aluno`, `email_aluno`, `nome_pai`, `telefone_pai`, `nome_mae`, `telefone_mae`, `nome_responsavel`, `telefone_resp`, `naturalidade`, `nacionalidade`, `rg`, `uf_rg`, `orgao_emissor`, `titulo_eleitor`, `zona`, `secao`, `certidao`, `uf_cert`, `cartorio_cert`, `modelo`, `numero`, `folha`, `livro`, `data_emissao_cert`, `municipio_cert`, `cpf`, `tipo_sanguineo`, `fazUsoMed`, `medicamentos`, `alergias`, `deficiencias`, `restric_alimentos`) VALUES (47,1,'ALUNO 47','1990-03-03','M',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `aluno`(`id_aluno`, `user_id`, `nome_aluno`, `nascimento`, `sexo`, `telefone_aluno`, `email_aluno`, `nome_pai`, `telefone_pai`, `nome_mae`, `telefone_mae`, `nome_responsavel`, `telefone_resp`, `naturalidade`, `nacionalidade`, `rg`, `uf_rg`, `orgao_emissor`, `titulo_eleitor`, `zona`, `secao`, `certidao`, `uf_cert`, `cartorio_cert`, `modelo`, `numero`, `folha`, `livro`, `data_emissao_cert`, `municipio_cert`, `cpf`, `tipo_sanguineo`, `fazUsoMed`, `medicamentos`, `alergias`, `deficiencias`, `restric_alimentos`) VALUES (48,1,'ALUNO 48','1990-03-03','M',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `aluno`(`id_aluno`, `user_id`, `nome_aluno`, `nascimento`, `sexo`, `telefone_aluno`, `email_aluno`, `nome_pai`, `telefone_pai`, `nome_mae`, `telefone_mae`, `nome_responsavel`, `telefone_resp`, `naturalidade`, `nacionalidade`, `rg`, `uf_rg`, `orgao_emissor`, `titulo_eleitor`, `zona`, `secao`, `certidao`, `uf_cert`, `cartorio_cert`, `modelo`, `numero`, `folha`, `livro`, `data_emissao_cert`, `municipio_cert`, `cpf`, `tipo_sanguineo`, `fazUsoMed`, `medicamentos`, `alergias`, `deficiencias`, `restric_alimentos`) VALUES (49,1,'ALUNO 49','1990-03-03','M',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `aluno`(`id_aluno`, `user_id`, `nome_aluno`, `nascimento`, `sexo`, `telefone_aluno`, `email_aluno`, `nome_pai`, `telefone_pai`, `nome_mae`, `telefone_mae`, `nome_responsavel`, `telefone_resp`, `naturalidade`, `nacionalidade`, `rg`, `uf_rg`, `orgao_emissor`, `titulo_eleitor`, `zona`, `secao`, `certidao`, `uf_cert`, `cartorio_cert`, `modelo`, `numero`, `folha`, `livro`, `data_emissao_cert`, `municipio_cert`, `cpf`, `tipo_sanguineo`, `fazUsoMed`, `medicamentos`, `alergias`, `deficiencias`, `restric_alimentos`) VALUES (50,1,'ALUNO 50','1990-03-03','M',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `aluno`(`id_aluno`, `user_id`, `nome_aluno`, `nascimento`, `sexo`, `telefone_aluno`, `email_aluno`, `nome_pai`, `telefone_pai`, `nome_mae`, `telefone_mae`, `nome_responsavel`, `telefone_resp`, `naturalidade`, `nacionalidade`, `rg`, `uf_rg`, `orgao_emissor`, `titulo_eleitor`, `zona`, `secao`, `certidao`, `uf_cert`, `cartorio_cert`, `modelo`, `numero`, `folha`, `livro`, `data_emissao_cert`, `municipio_cert`, `cpf`, `tipo_sanguineo`, `fazUsoMed`, `medicamentos`, `alergias`, `deficiencias`, `restric_alimentos`) VALUES (51,1,'ALUNO 51','1990-03-03','M',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `aluno`(`id_aluno`, `user_id`, `nome_aluno`, `nascimento`, `sexo`, `telefone_aluno`, `email_aluno`, `nome_pai`, `telefone_pai`, `nome_mae`, `telefone_mae`, `nome_responsavel`, `telefone_resp`, `naturalidade`, `nacionalidade`, `rg`, `uf_rg`, `orgao_emissor`, `titulo_eleitor`, `zona`, `secao`, `certidao`, `uf_cert`, `cartorio_cert`, `modelo`, `numero`, `folha`, `livro`, `data_emissao_cert`, `municipio_cert`, `cpf`, `tipo_sanguineo`, `fazUsoMed`, `medicamentos`, `alergias`, `deficiencias`, `restric_alimentos`) VALUES (52,1,'ALUNO 52','1990-03-03','M',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `aluno`(`id_aluno`, `user_id`, `nome_aluno`, `nascimento`, `sexo`, `telefone_aluno`, `email_aluno`, `nome_pai`, `telefone_pai`, `nome_mae`, `telefone_mae`, `nome_responsavel`, `telefone_resp`, `naturalidade`, `nacionalidade`, `rg`, `uf_rg`, `orgao_emissor`, `titulo_eleitor`, `zona`, `secao`, `certidao`, `uf_cert`, `cartorio_cert`, `modelo`, `numero`, `folha`, `livro`, `data_emissao_cert`, `municipio_cert`, `cpf`, `tipo_sanguineo`, `fazUsoMed`, `medicamentos`, `alergias`, `deficiencias`, `restric_alimentos`) VALUES (53,1,'ALUNO 53','1990-03-03','M',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `aluno`(`id_aluno`, `user_id`, `nome_aluno`, `nascimento`, `sexo`, `telefone_aluno`, `email_aluno`, `nome_pai`, `telefone_pai`, `nome_mae`, `telefone_mae`, `nome_responsavel`, `telefone_resp`, `naturalidade`, `nacionalidade`, `rg`, `uf_rg`, `orgao_emissor`, `titulo_eleitor`, `zona`, `secao`, `certidao`, `uf_cert`, `cartorio_cert`, `modelo`, `numero`, `folha`, `livro`, `data_emissao_cert`, `municipio_cert`, `cpf`, `tipo_sanguineo`, `fazUsoMed`, `medicamentos`, `alergias`, `deficiencias`, `restric_alimentos`) VALUES (54,1,'ALUNO 54','1990-03-03','M',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `aluno`(`id_aluno`, `user_id`, `nome_aluno`, `nascimento`, `sexo`, `telefone_aluno`, `email_aluno`, `nome_pai`, `telefone_pai`, `nome_mae`, `telefone_mae`, `nome_responsavel`, `telefone_resp`, `naturalidade`, `nacionalidade`, `rg`, `uf_rg`, `orgao_emissor`, `titulo_eleitor`, `zona`, `secao`, `certidao`, `uf_cert`, `cartorio_cert`, `modelo`, `numero`, `folha`, `livro`, `data_emissao_cert`, `municipio_cert`, `cpf`, `tipo_sanguineo`, `fazUsoMed`, `medicamentos`, `alergias`, `deficiencias`, `restric_alimentos`) VALUES (55,1,'ALUNO 55','1990-03-03','M',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `aluno`(`id_aluno`, `user_id`, `nome_aluno`, `nascimento`, `sexo`, `telefone_aluno`, `email_aluno`, `nome_pai`, `telefone_pai`, `nome_mae`, `telefone_mae`, `nome_responsavel`, `telefone_resp`, `naturalidade`, `nacionalidade`, `rg`, `uf_rg`, `orgao_emissor`, `titulo_eleitor`, `zona`, `secao`, `certidao`, `uf_cert`, `cartorio_cert`, `modelo`, `numero`, `folha`, `livro`, `data_emissao_cert`, `municipio_cert`, `cpf`, `tipo_sanguineo`, `fazUsoMed`, `medicamentos`, `alergias`, `deficiencias`, `restric_alimentos`) VALUES (56,1,'ALUNO 56','1990-03-03','M',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `aluno`(`id_aluno`, `user_id`, `nome_aluno`, `nascimento`, `sexo`, `telefone_aluno`, `email_aluno`, `nome_pai`, `telefone_pai`, `nome_mae`, `telefone_mae`, `nome_responsavel`, `telefone_resp`, `naturalidade`, `nacionalidade`, `rg`, `uf_rg`, `orgao_emissor`, `titulo_eleitor`, `zona`, `secao`, `certidao`, `uf_cert`, `cartorio_cert`, `modelo`, `numero`, `folha`, `livro`, `data_emissao_cert`, `municipio_cert`, `cpf`, `tipo_sanguineo`, `fazUsoMed`, `medicamentos`, `alergias`, `deficiencias`, `restric_alimentos`) VALUES (57,1,'ALUNO 57','1990-03-03','M',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `aluno`(`id_aluno`, `user_id`, `nome_aluno`, `nascimento`, `sexo`, `telefone_aluno`, `email_aluno`, `nome_pai`, `telefone_pai`, `nome_mae`, `telefone_mae`, `nome_responsavel`, `telefone_resp`, `naturalidade`, `nacionalidade`, `rg`, `uf_rg`, `orgao_emissor`, `titulo_eleitor`, `zona`, `secao`, `certidao`, `uf_cert`, `cartorio_cert`, `modelo`, `numero`, `folha`, `livro`, `data_emissao_cert`, `municipio_cert`, `cpf`, `tipo_sanguineo`, `fazUsoMed`, `medicamentos`, `alergias`, `deficiencias`, `restric_alimentos`) VALUES (58,1,'ALUNO 58','1990-03-03','M',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `aluno`(`id_aluno`, `user_id`, `nome_aluno`, `nascimento`, `sexo`, `telefone_aluno`, `email_aluno`, `nome_pai`, `telefone_pai`, `nome_mae`, `telefone_mae`, `nome_responsavel`, `telefone_resp`, `naturalidade`, `nacionalidade`, `rg`, `uf_rg`, `orgao_emissor`, `titulo_eleitor`, `zona`, `secao`, `certidao`, `uf_cert`, `cartorio_cert`, `modelo`, `numero`, `folha`, `livro`, `data_emissao_cert`, `municipio_cert`, `cpf`, `tipo_sanguineo`, `fazUsoMed`, `medicamentos`, `alergias`, `deficiencias`, `restric_alimentos`) VALUES (59,1,'ALUNO 59','1990-03-03','M',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `aluno`(`id_aluno`, `user_id`, `nome_aluno`, `nascimento`, `sexo`, `telefone_aluno`, `email_aluno`, `nome_pai`, `telefone_pai`, `nome_mae`, `telefone_mae`, `nome_responsavel`, `telefone_resp`, `naturalidade`, `nacionalidade`, `rg`, `uf_rg`, `orgao_emissor`, `titulo_eleitor`, `zona`, `secao`, `certidao`, `uf_cert`, `cartorio_cert`, `modelo`, `numero`, `folha`, `livro`, `data_emissao_cert`, `municipio_cert`, `cpf`, `tipo_sanguineo`, `fazUsoMed`, `medicamentos`, `alergias`, `deficiencias`, `restric_alimentos`) VALUES (60,1,'ALUNO 60','1990-03-03','M',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `aluno`(`id_aluno`, `user_id`, `nome_aluno`, `nascimento`, `sexo`, `telefone_aluno`, `email_aluno`, `nome_pai`, `telefone_pai`, `nome_mae`, `telefone_mae`, `nome_responsavel`, `telefone_resp`, `naturalidade`, `nacionalidade`, `rg`, `uf_rg`, `orgao_emissor`, `titulo_eleitor`, `zona`, `secao`, `certidao`, `uf_cert`, `cartorio_cert`, `modelo`, `numero`, `folha`, `livro`, `data_emissao_cert`, `municipio_cert`, `cpf`, `tipo_sanguineo`, `fazUsoMed`, `medicamentos`, `alergias`, `deficiencias`, `restric_alimentos`) VALUES (61,1,'ALUNO 61','1990-03-03','M',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `aluno`(`id_aluno`, `user_id`, `nome_aluno`, `nascimento`, `sexo`, `telefone_aluno`, `email_aluno`, `nome_pai`, `telefone_pai`, `nome_mae`, `telefone_mae`, `nome_responsavel`, `telefone_resp`, `naturalidade`, `nacionalidade`, `rg`, `uf_rg`, `orgao_emissor`, `titulo_eleitor`, `zona`, `secao`, `certidao`, `uf_cert`, `cartorio_cert`, `modelo`, `numero`, `folha`, `livro`, `data_emissao_cert`, `municipio_cert`, `cpf`, `tipo_sanguineo`, `fazUsoMed`, `medicamentos`, `alergias`, `deficiencias`, `restric_alimentos`) VALUES (62,1,'ALUNO 62','1990-03-03','M',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `aluno`(`id_aluno`, `user_id`, `nome_aluno`, `nascimento`, `sexo`, `telefone_aluno`, `email_aluno`, `nome_pai`, `telefone_pai`, `nome_mae`, `telefone_mae`, `nome_responsavel`, `telefone_resp`, `naturalidade`, `nacionalidade`, `rg`, `uf_rg`, `orgao_emissor`, `titulo_eleitor`, `zona`, `secao`, `certidao`, `uf_cert`, `cartorio_cert`, `modelo`, `numero`, `folha`, `livro`, `data_emissao_cert`, `municipio_cert`, `cpf`, `tipo_sanguineo`, `fazUsoMed`, `medicamentos`, `alergias`, `deficiencias`, `restric_alimentos`) VALUES (63,1,'ALUNO 63','1990-03-03','M',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `aluno`(`id_aluno`, `user_id`, `nome_aluno`, `nascimento`, `sexo`, `telefone_aluno`, `email_aluno`, `nome_pai`, `telefone_pai`, `nome_mae`, `telefone_mae`, `nome_responsavel`, `telefone_resp`, `naturalidade`, `nacionalidade`, `rg`, `uf_rg`, `orgao_emissor`, `titulo_eleitor`, `zona`, `secao`, `certidao`, `uf_cert`, `cartorio_cert`, `modelo`, `numero`, `folha`, `livro`, `data_emissao_cert`, `municipio_cert`, `cpf`, `tipo_sanguineo`, `fazUsoMed`, `medicamentos`, `alergias`, `deficiencias`, `restric_alimentos`) VALUES (64,1,'ALUNO 64','1990-03-03','M',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `aluno`(`id_aluno`, `user_id`, `nome_aluno`, `nascimento`, `sexo`, `telefone_aluno`, `email_aluno`, `nome_pai`, `telefone_pai`, `nome_mae`, `telefone_mae`, `nome_responsavel`, `telefone_resp`, `naturalidade`, `nacionalidade`, `rg`, `uf_rg`, `orgao_emissor`, `titulo_eleitor`, `zona`, `secao`, `certidao`, `uf_cert`, `cartorio_cert`, `modelo`, `numero`, `folha`, `livro`, `data_emissao_cert`, `municipio_cert`, `cpf`, `tipo_sanguineo`, `fazUsoMed`, `medicamentos`, `alergias`, `deficiencias`, `restric_alimentos`) VALUES (65,1,'ALUNO 65','1990-03-03','M',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `aluno`(`id_aluno`, `user_id`, `nome_aluno`, `nascimento`, `sexo`, `telefone_aluno`, `email_aluno`, `nome_pai`, `telefone_pai`, `nome_mae`, `telefone_mae`, `nome_responsavel`, `telefone_resp`, `naturalidade`, `nacionalidade`, `rg`, `uf_rg`, `orgao_emissor`, `titulo_eleitor`, `zona`, `secao`, `certidao`, `uf_cert`, `cartorio_cert`, `modelo`, `numero`, `folha`, `livro`, `data_emissao_cert`, `municipio_cert`, `cpf`, `tipo_sanguineo`, `fazUsoMed`, `medicamentos`, `alergias`, `deficiencias`, `restric_alimentos`) VALUES (66,1,'ALUNO 66','1990-03-03','M',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `aluno`(`id_aluno`, `user_id`, `nome_aluno`, `nascimento`, `sexo`, `telefone_aluno`, `email_aluno`, `nome_pai`, `telefone_pai`, `nome_mae`, `telefone_mae`, `nome_responsavel`, `telefone_resp`, `naturalidade`, `nacionalidade`, `rg`, `uf_rg`, `orgao_emissor`, `titulo_eleitor`, `zona`, `secao`, `certidao`, `uf_cert`, `cartorio_cert`, `modelo`, `numero`, `folha`, `livro`, `data_emissao_cert`, `municipio_cert`, `cpf`, `tipo_sanguineo`, `fazUsoMed`, `medicamentos`, `alergias`, `deficiencias`, `restric_alimentos`) VALUES (67,1,'ALUNO 67','1990-03-03','M',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `aluno`(`id_aluno`, `user_id`, `nome_aluno`, `nascimento`, `sexo`, `telefone_aluno`, `email_aluno`, `nome_pai`, `telefone_pai`, `nome_mae`, `telefone_mae`, `nome_responsavel`, `telefone_resp`, `naturalidade`, `nacionalidade`, `rg`, `uf_rg`, `orgao_emissor`, `titulo_eleitor`, `zona`, `secao`, `certidao`, `uf_cert`, `cartorio_cert`, `modelo`, `numero`, `folha`, `livro`, `data_emissao_cert`, `municipio_cert`, `cpf`, `tipo_sanguineo`, `fazUsoMed`, `medicamentos`, `alergias`, `deficiencias`, `restric_alimentos`) VALUES (68,1,'ALUNO 68','1990-03-03','M',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `aluno`(`id_aluno`, `user_id`, `nome_aluno`, `nascimento`, `sexo`, `telefone_aluno`, `email_aluno`, `nome_pai`, `telefone_pai`, `nome_mae`, `telefone_mae`, `nome_responsavel`, `telefone_resp`, `naturalidade`, `nacionalidade`, `rg`, `uf_rg`, `orgao_emissor`, `titulo_eleitor`, `zona`, `secao`, `certidao`, `uf_cert`, `cartorio_cert`, `modelo`, `numero`, `folha`, `livro`, `data_emissao_cert`, `municipio_cert`, `cpf`, `tipo_sanguineo`, `fazUsoMed`, `medicamentos`, `alergias`, `deficiencias`, `restric_alimentos`) VALUES (69,1,'ALUNO 69','1990-03-03','M',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `aluno`(`id_aluno`, `user_id`, `nome_aluno`, `nascimento`, `sexo`, `telefone_aluno`, `email_aluno`, `nome_pai`, `telefone_pai`, `nome_mae`, `telefone_mae`, `nome_responsavel`, `telefone_resp`, `naturalidade`, `nacionalidade`, `rg`, `uf_rg`, `orgao_emissor`, `titulo_eleitor`, `zona`, `secao`, `certidao`, `uf_cert`, `cartorio_cert`, `modelo`, `numero`, `folha`, `livro`, `data_emissao_cert`, `municipio_cert`, `cpf`, `tipo_sanguineo`, `fazUsoMed`, `medicamentos`, `alergias`, `deficiencias`, `restric_alimentos`) VALUES (70,1,'ALUNO 70','1990-03-03','M',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `aluno`(`id_aluno`, `user_id`, `nome_aluno`, `nascimento`, `sexo`, `telefone_aluno`, `email_aluno`, `nome_pai`, `telefone_pai`, `nome_mae`, `telefone_mae`, `nome_responsavel`, `telefone_resp`, `naturalidade`, `nacionalidade`, `rg`, `uf_rg`, `orgao_emissor`, `titulo_eleitor`, `zona`, `secao`, `certidao`, `uf_cert`, `cartorio_cert`, `modelo`, `numero`, `folha`, `livro`, `data_emissao_cert`, `municipio_cert`, `cpf`, `tipo_sanguineo`, `fazUsoMed`, `medicamentos`, `alergias`, `deficiencias`, `restric_alimentos`) VALUES (71,1,'ALUNO 71','1990-03-03','M',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `aluno`(`id_aluno`, `user_id`, `nome_aluno`, `nascimento`, `sexo`, `telefone_aluno`, `email_aluno`, `nome_pai`, `telefone_pai`, `nome_mae`, `telefone_mae`, `nome_responsavel`, `telefone_resp`, `naturalidade`, `nacionalidade`, `rg`, `uf_rg`, `orgao_emissor`, `titulo_eleitor`, `zona`, `secao`, `certidao`, `uf_cert`, `cartorio_cert`, `modelo`, `numero`, `folha`, `livro`, `data_emissao_cert`, `municipio_cert`, `cpf`, `tipo_sanguineo`, `fazUsoMed`, `medicamentos`, `alergias`, `deficiencias`, `restric_alimentos`) VALUES (72,1,'ALUNO 72','1990-03-03','M',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
																																																																			
																																																																			



INSERT INTO `dados_anuais`(`id_da`, `aluno_id`, `escola_id`, `ano`, `tam_moletom`, `tam_camiseta`, `tam_calca`, `tam_bermuda`, `tam_calcado`, `tam_meia`, `etapa`, `turno`) VALUES (01,01,04,2020,01,01,01,01,01,01,01,"M");
INSERT INTO `dados_anuais`(`id_da`, `aluno_id`, `escola_id`, `ano`, `tam_moletom`, `tam_camiseta`, `tam_calca`, `tam_bermuda`, `tam_calcado`, `tam_meia`, `etapa`, `turno`) VALUES (02,02,05,2020,02,02,02,02,02,02,02,"M");
INSERT INTO `dados_anuais`(`id_da`, `aluno_id`, `escola_id`, `ano`, `tam_moletom`, `tam_camiseta`, `tam_calca`, `tam_bermuda`, `tam_calcado`, `tam_meia`, `etapa`, `turno`) VALUES (03,03,06,2020,03,03,03,03,03,03,03,"M");
INSERT INTO `dados_anuais`(`id_da`, `aluno_id`, `escola_id`, `ano`, `tam_moletom`, `tam_camiseta`, `tam_calca`, `tam_bermuda`, `tam_calcado`, `tam_meia`, `etapa`, `turno`) VALUES (04,04,07,2020,04,04,04,04,04,04,04,"M");
INSERT INTO `dados_anuais`(`id_da`, `aluno_id`, `escola_id`, `ano`, `tam_moletom`, `tam_camiseta`, `tam_calca`, `tam_bermuda`, `tam_calcado`, `tam_meia`, `etapa`, `turno`) VALUES (05,05,08,2020,05,05,05,05,05,05,01,"M");
INSERT INTO `dados_anuais`(`id_da`, `aluno_id`, `escola_id`, `ano`, `tam_moletom`, `tam_camiseta`, `tam_calca`, `tam_bermuda`, `tam_calcado`, `tam_meia`, `etapa`, `turno`) VALUES (06,06,09,2020,06,06,06,06,06,06,02,"M");
INSERT INTO `dados_anuais`(`id_da`, `aluno_id`, `escola_id`, `ano`, `tam_moletom`, `tam_camiseta`, `tam_calca`, `tam_bermuda`, `tam_calcado`, `tam_meia`, `etapa`, `turno`) VALUES (07,07,10,2020,07,07,07,07,07,07,03,"M");
INSERT INTO `dados_anuais`(`id_da`, `aluno_id`, `escola_id`, `ano`, `tam_moletom`, `tam_camiseta`, `tam_calca`, `tam_bermuda`, `tam_calcado`, `tam_meia`, `etapa`, `turno`) VALUES (08,08,11,2020,08,08,08,08,08,08,04,"M");
INSERT INTO `dados_anuais`(`id_da`, `aluno_id`, `escola_id`, `ano`, `tam_moletom`, `tam_camiseta`, `tam_calca`, `tam_bermuda`, `tam_calcado`, `tam_meia`, `etapa`, `turno`) VALUES (09,09,12,2020,01,01,01,01,01,01,01,"M");
INSERT INTO `dados_anuais`(`id_da`, `aluno_id`, `escola_id`, `ano`, `tam_moletom`, `tam_camiseta`, `tam_calca`, `tam_bermuda`, `tam_calcado`, `tam_meia`, `etapa`, `turno`) VALUES (10,10,04,2020,02,02,02,02,02,02,02,"M");
INSERT INTO `dados_anuais`(`id_da`, `aluno_id`, `escola_id`, `ano`, `tam_moletom`, `tam_camiseta`, `tam_calca`, `tam_bermuda`, `tam_calcado`, `tam_meia`, `etapa`, `turno`) VALUES (11,11,05,2020,03,03,03,03,03,03,03,"M");
INSERT INTO `dados_anuais`(`id_da`, `aluno_id`, `escola_id`, `ano`, `tam_moletom`, `tam_camiseta`, `tam_calca`, `tam_bermuda`, `tam_calcado`, `tam_meia`, `etapa`, `turno`) VALUES (12,12,06,2020,04,04,04,04,04,04,04,"M");
INSERT INTO `dados_anuais`(`id_da`, `aluno_id`, `escola_id`, `ano`, `tam_moletom`, `tam_camiseta`, `tam_calca`, `tam_bermuda`, `tam_calcado`, `tam_meia`, `etapa`, `turno`) VALUES (13,13,07,2020,05,05,05,05,05,05,01,"M");
INSERT INTO `dados_anuais`(`id_da`, `aluno_id`, `escola_id`, `ano`, `tam_moletom`, `tam_camiseta`, `tam_calca`, `tam_bermuda`, `tam_calcado`, `tam_meia`, `etapa`, `turno`) VALUES (14,14,08,2020,06,06,06,06,06,06,02,"M");
INSERT INTO `dados_anuais`(`id_da`, `aluno_id`, `escola_id`, `ano`, `tam_moletom`, `tam_camiseta`, `tam_calca`, `tam_bermuda`, `tam_calcado`, `tam_meia`, `etapa`, `turno`) VALUES (15,15,09,2020,07,07,07,07,07,07,03,"M");
INSERT INTO `dados_anuais`(`id_da`, `aluno_id`, `escola_id`, `ano`, `tam_moletom`, `tam_camiseta`, `tam_calca`, `tam_bermuda`, `tam_calcado`, `tam_meia`, `etapa`, `turno`) VALUES (16,16,10,2020,08,08,08,08,08,08,04,"M");
INSERT INTO `dados_anuais`(`id_da`, `aluno_id`, `escola_id`, `ano`, `tam_moletom`, `tam_camiseta`, `tam_calca`, `tam_bermuda`, `tam_calcado`, `tam_meia`, `etapa`, `turno`) VALUES (17,17,11,2020,01,01,01,01,01,01,01,"M");
INSERT INTO `dados_anuais`(`id_da`, `aluno_id`, `escola_id`, `ano`, `tam_moletom`, `tam_camiseta`, `tam_calca`, `tam_bermuda`, `tam_calcado`, `tam_meia`, `etapa`, `turno`) VALUES (18,18,12,2020,02,02,02,02,02,02,02,"M");
INSERT INTO `dados_anuais`(`id_da`, `aluno_id`, `escola_id`, `ano`, `tam_moletom`, `tam_camiseta`, `tam_calca`, `tam_bermuda`, `tam_calcado`, `tam_meia`, `etapa`, `turno`) VALUES (19,19,04,2020,03,03,03,03,03,03,03,"M");
INSERT INTO `dados_anuais`(`id_da`, `aluno_id`, `escola_id`, `ano`, `tam_moletom`, `tam_camiseta`, `tam_calca`, `tam_bermuda`, `tam_calcado`, `tam_meia`, `etapa`, `turno`) VALUES (20,20,05,2020,04,04,04,04,04,04,04,"M");
INSERT INTO `dados_anuais`(`id_da`, `aluno_id`, `escola_id`, `ano`, `tam_moletom`, `tam_camiseta`, `tam_calca`, `tam_bermuda`, `tam_calcado`, `tam_meia`, `etapa`, `turno`) VALUES (21,21,06,2020,05,05,05,05,05,05,01,"M");
INSERT INTO `dados_anuais`(`id_da`, `aluno_id`, `escola_id`, `ano`, `tam_moletom`, `tam_camiseta`, `tam_calca`, `tam_bermuda`, `tam_calcado`, `tam_meia`, `etapa`, `turno`) VALUES (22,22,07,2020,06,06,06,06,06,06,02,"M");
INSERT INTO `dados_anuais`(`id_da`, `aluno_id`, `escola_id`, `ano`, `tam_moletom`, `tam_camiseta`, `tam_calca`, `tam_bermuda`, `tam_calcado`, `tam_meia`, `etapa`, `turno`) VALUES (23,23,08,2020,07,07,07,07,07,07,03,"M");
INSERT INTO `dados_anuais`(`id_da`, `aluno_id`, `escola_id`, `ano`, `tam_moletom`, `tam_camiseta`, `tam_calca`, `tam_bermuda`, `tam_calcado`, `tam_meia`, `etapa`, `turno`) VALUES (24,24,09,2020,08,08,08,08,08,08,04,"M");
INSERT INTO `dados_anuais`(`id_da`, `aluno_id`, `escola_id`, `ano`, `tam_moletom`, `tam_camiseta`, `tam_calca`, `tam_bermuda`, `tam_calcado`, `tam_meia`, `etapa`, `turno`) VALUES (25,25,10,2020,01,01,01,01,01,01,01,"M");
INSERT INTO `dados_anuais`(`id_da`, `aluno_id`, `escola_id`, `ano`, `tam_moletom`, `tam_camiseta`, `tam_calca`, `tam_bermuda`, `tam_calcado`, `tam_meia`, `etapa`, `turno`) VALUES (26,26,11,2020,02,02,02,02,02,02,02,"M");
INSERT INTO `dados_anuais`(`id_da`, `aluno_id`, `escola_id`, `ano`, `tam_moletom`, `tam_camiseta`, `tam_calca`, `tam_bermuda`, `tam_calcado`, `tam_meia`, `etapa`, `turno`) VALUES (27,27,12,2020,03,03,03,03,03,03,03,"M");
INSERT INTO `dados_anuais`(`id_da`, `aluno_id`, `escola_id`, `ano`, `tam_moletom`, `tam_camiseta`, `tam_calca`, `tam_bermuda`, `tam_calcado`, `tam_meia`, `etapa`, `turno`) VALUES (28,28,04,2020,04,04,04,04,04,04,04,"M");
INSERT INTO `dados_anuais`(`id_da`, `aluno_id`, `escola_id`, `ano`, `tam_moletom`, `tam_camiseta`, `tam_calca`, `tam_bermuda`, `tam_calcado`, `tam_meia`, `etapa`, `turno`) VALUES (29,29,05,2020,05,05,05,05,05,05,01,"M");
INSERT INTO `dados_anuais`(`id_da`, `aluno_id`, `escola_id`, `ano`, `tam_moletom`, `tam_camiseta`, `tam_calca`, `tam_bermuda`, `tam_calcado`, `tam_meia`, `etapa`, `turno`) VALUES (30,30,06,2020,06,06,06,06,06,06,02,"M");
INSERT INTO `dados_anuais`(`id_da`, `aluno_id`, `escola_id`, `ano`, `tam_moletom`, `tam_camiseta`, `tam_calca`, `tam_bermuda`, `tam_calcado`, `tam_meia`, `etapa`, `turno`) VALUES (31,31,07,2020,07,07,07,07,07,07,03,"M");
INSERT INTO `dados_anuais`(`id_da`, `aluno_id`, `escola_id`, `ano`, `tam_moletom`, `tam_camiseta`, `tam_calca`, `tam_bermuda`, `tam_calcado`, `tam_meia`, `etapa`, `turno`) VALUES (32,32,08,2020,08,08,08,08,08,08,04,"M");
INSERT INTO `dados_anuais`(`id_da`, `aluno_id`, `escola_id`, `ano`, `tam_moletom`, `tam_camiseta`, `tam_calca`, `tam_bermuda`, `tam_calcado`, `tam_meia`, `etapa`, `turno`) VALUES (33,33,09,2020,01,01,01,01,01,01,01,"M");
INSERT INTO `dados_anuais`(`id_da`, `aluno_id`, `escola_id`, `ano`, `tam_moletom`, `tam_camiseta`, `tam_calca`, `tam_bermuda`, `tam_calcado`, `tam_meia`, `etapa`, `turno`) VALUES (34,34,10,2020,02,02,02,02,02,02,02,"M");
INSERT INTO `dados_anuais`(`id_da`, `aluno_id`, `escola_id`, `ano`, `tam_moletom`, `tam_camiseta`, `tam_calca`, `tam_bermuda`, `tam_calcado`, `tam_meia`, `etapa`, `turno`) VALUES (35,35,11,2020,03,03,03,03,03,03,03,"M");
INSERT INTO `dados_anuais`(`id_da`, `aluno_id`, `escola_id`, `ano`, `tam_moletom`, `tam_camiseta`, `tam_calca`, `tam_bermuda`, `tam_calcado`, `tam_meia`, `etapa`, `turno`) VALUES (36,36,12,2020,04,04,04,04,04,04,04,"M");
INSERT INTO `dados_anuais`(`id_da`, `aluno_id`, `escola_id`, `ano`, `tam_moletom`, `tam_camiseta`, `tam_calca`, `tam_bermuda`, `tam_calcado`, `tam_meia`, `etapa`, `turno`) VALUES (37,37,04,2020,05,05,05,05,05,05,01,"M");
INSERT INTO `dados_anuais`(`id_da`, `aluno_id`, `escola_id`, `ano`, `tam_moletom`, `tam_camiseta`, `tam_calca`, `tam_bermuda`, `tam_calcado`, `tam_meia`, `etapa`, `turno`) VALUES (38,38,05,2020,06,06,06,06,06,06,02,"M");
INSERT INTO `dados_anuais`(`id_da`, `aluno_id`, `escola_id`, `ano`, `tam_moletom`, `tam_camiseta`, `tam_calca`, `tam_bermuda`, `tam_calcado`, `tam_meia`, `etapa`, `turno`) VALUES (39,39,06,2020,07,07,07,07,07,07,03,"M");
INSERT INTO `dados_anuais`(`id_da`, `aluno_id`, `escola_id`, `ano`, `tam_moletom`, `tam_camiseta`, `tam_calca`, `tam_bermuda`, `tam_calcado`, `tam_meia`, `etapa`, `turno`) VALUES (40,40,07,2020,08,08,08,08,08,08,04,"M");
INSERT INTO `dados_anuais`(`id_da`, `aluno_id`, `escola_id`, `ano`, `tam_moletom`, `tam_camiseta`, `tam_calca`, `tam_bermuda`, `tam_calcado`, `tam_meia`, `etapa`, `turno`) VALUES (41,41,08,2020,01,01,01,01,01,01,01,"M");
INSERT INTO `dados_anuais`(`id_da`, `aluno_id`, `escola_id`, `ano`, `tam_moletom`, `tam_camiseta`, `tam_calca`, `tam_bermuda`, `tam_calcado`, `tam_meia`, `etapa`, `turno`) VALUES (42,42,09,2020,02,02,02,02,02,02,02,"M");
INSERT INTO `dados_anuais`(`id_da`, `aluno_id`, `escola_id`, `ano`, `tam_moletom`, `tam_camiseta`, `tam_calca`, `tam_bermuda`, `tam_calcado`, `tam_meia`, `etapa`, `turno`) VALUES (43,43,10,2020,03,03,03,03,03,03,03,"M");
INSERT INTO `dados_anuais`(`id_da`, `aluno_id`, `escola_id`, `ano`, `tam_moletom`, `tam_camiseta`, `tam_calca`, `tam_bermuda`, `tam_calcado`, `tam_meia`, `etapa`, `turno`) VALUES (44,44,11,2020,04,04,04,04,04,04,04,"M");
INSERT INTO `dados_anuais`(`id_da`, `aluno_id`, `escola_id`, `ano`, `tam_moletom`, `tam_camiseta`, `tam_calca`, `tam_bermuda`, `tam_calcado`, `tam_meia`, `etapa`, `turno`) VALUES (45,45,12,2020,05,05,05,05,05,05,01,"M");
INSERT INTO `dados_anuais`(`id_da`, `aluno_id`, `escola_id`, `ano`, `tam_moletom`, `tam_camiseta`, `tam_calca`, `tam_bermuda`, `tam_calcado`, `tam_meia`, `etapa`, `turno`) VALUES (46,46,04,2020,06,06,06,06,06,06,02,"M");
INSERT INTO `dados_anuais`(`id_da`, `aluno_id`, `escola_id`, `ano`, `tam_moletom`, `tam_camiseta`, `tam_calca`, `tam_bermuda`, `tam_calcado`, `tam_meia`, `etapa`, `turno`) VALUES (47,47,05,2020,07,07,07,07,07,07,03,"M");
INSERT INTO `dados_anuais`(`id_da`, `aluno_id`, `escola_id`, `ano`, `tam_moletom`, `tam_camiseta`, `tam_calca`, `tam_bermuda`, `tam_calcado`, `tam_meia`, `etapa`, `turno`) VALUES (48,48,06,2020,08,08,08,08,08,08,04,"M");
INSERT INTO `dados_anuais`(`id_da`, `aluno_id`, `escola_id`, `ano`, `tam_moletom`, `tam_camiseta`, `tam_calca`, `tam_bermuda`, `tam_calcado`, `tam_meia`, `etapa`, `turno`) VALUES (49,49,07,2020,01,01,01,01,01,01,01,"M");
INSERT INTO `dados_anuais`(`id_da`, `aluno_id`, `escola_id`, `ano`, `tam_moletom`, `tam_camiseta`, `tam_calca`, `tam_bermuda`, `tam_calcado`, `tam_meia`, `etapa`, `turno`) VALUES (50,50,08,2020,02,02,02,02,02,02,02,"M");
INSERT INTO `dados_anuais`(`id_da`, `aluno_id`, `escola_id`, `ano`, `tam_moletom`, `tam_camiseta`, `tam_calca`, `tam_bermuda`, `tam_calcado`, `tam_meia`, `etapa`, `turno`) VALUES (51,51,09,2020,03,03,03,03,03,03,03,"M");
INSERT INTO `dados_anuais`(`id_da`, `aluno_id`, `escola_id`, `ano`, `tam_moletom`, `tam_camiseta`, `tam_calca`, `tam_bermuda`, `tam_calcado`, `tam_meia`, `etapa`, `turno`) VALUES (52,52,10,2020,04,04,04,04,04,04,04,"M");
INSERT INTO `dados_anuais`(`id_da`, `aluno_id`, `escola_id`, `ano`, `tam_moletom`, `tam_camiseta`, `tam_calca`, `tam_bermuda`, `tam_calcado`, `tam_meia`, `etapa`, `turno`) VALUES (53,53,11,2020,05,05,05,05,05,05,01,"M");
INSERT INTO `dados_anuais`(`id_da`, `aluno_id`, `escola_id`, `ano`, `tam_moletom`, `tam_camiseta`, `tam_calca`, `tam_bermuda`, `tam_calcado`, `tam_meia`, `etapa`, `turno`) VALUES (54,54,12,2020,06,06,06,06,06,06,02,"M");
INSERT INTO `dados_anuais`(`id_da`, `aluno_id`, `escola_id`, `ano`, `tam_moletom`, `tam_camiseta`, `tam_calca`, `tam_bermuda`, `tam_calcado`, `tam_meia`, `etapa`, `turno`) VALUES (55,55,04,2020,07,07,07,07,07,07,03,"M");
INSERT INTO `dados_anuais`(`id_da`, `aluno_id`, `escola_id`, `ano`, `tam_moletom`, `tam_camiseta`, `tam_calca`, `tam_bermuda`, `tam_calcado`, `tam_meia`, `etapa`, `turno`) VALUES (56,56,05,2020,08,08,08,08,08,08,04,"M");
INSERT INTO `dados_anuais`(`id_da`, `aluno_id`, `escola_id`, `ano`, `tam_moletom`, `tam_camiseta`, `tam_calca`, `tam_bermuda`, `tam_calcado`, `tam_meia`, `etapa`, `turno`) VALUES (57,57,06,2020,01,01,01,01,01,01,01,"M");
INSERT INTO `dados_anuais`(`id_da`, `aluno_id`, `escola_id`, `ano`, `tam_moletom`, `tam_camiseta`, `tam_calca`, `tam_bermuda`, `tam_calcado`, `tam_meia`, `etapa`, `turno`) VALUES (58,58,07,2020,02,02,02,02,02,02,02,"M");
INSERT INTO `dados_anuais`(`id_da`, `aluno_id`, `escola_id`, `ano`, `tam_moletom`, `tam_camiseta`, `tam_calca`, `tam_bermuda`, `tam_calcado`, `tam_meia`, `etapa`, `turno`) VALUES (59,59,08,2020,03,03,03,03,03,03,03,"M");
INSERT INTO `dados_anuais`(`id_da`, `aluno_id`, `escola_id`, `ano`, `tam_moletom`, `tam_camiseta`, `tam_calca`, `tam_bermuda`, `tam_calcado`, `tam_meia`, `etapa`, `turno`) VALUES (60,60,09,2020,04,04,04,04,04,04,04,"M");
INSERT INTO `dados_anuais`(`id_da`, `aluno_id`, `escola_id`, `ano`, `tam_moletom`, `tam_camiseta`, `tam_calca`, `tam_bermuda`, `tam_calcado`, `tam_meia`, `etapa`, `turno`) VALUES (61,61,10,2020,05,05,05,05,05,05,01,"M");
INSERT INTO `dados_anuais`(`id_da`, `aluno_id`, `escola_id`, `ano`, `tam_moletom`, `tam_camiseta`, `tam_calca`, `tam_bermuda`, `tam_calcado`, `tam_meia`, `etapa`, `turno`) VALUES (62,62,11,2020,06,06,06,06,06,06,02,"M");
INSERT INTO `dados_anuais`(`id_da`, `aluno_id`, `escola_id`, `ano`, `tam_moletom`, `tam_camiseta`, `tam_calca`, `tam_bermuda`, `tam_calcado`, `tam_meia`, `etapa`, `turno`) VALUES (63,63,12,2020,07,07,07,07,07,07,03,"M");
INSERT INTO `dados_anuais`(`id_da`, `aluno_id`, `escola_id`, `ano`, `tam_moletom`, `tam_camiseta`, `tam_calca`, `tam_bermuda`, `tam_calcado`, `tam_meia`, `etapa`, `turno`) VALUES (64,64,04,2020,08,08,08,08,08,08,04,"M");
INSERT INTO `dados_anuais`(`id_da`, `aluno_id`, `escola_id`, `ano`, `tam_moletom`, `tam_camiseta`, `tam_calca`, `tam_bermuda`, `tam_calcado`, `tam_meia`, `etapa`, `turno`) VALUES (65,65,05,2020,01,01,01,01,01,01,01,"M");
INSERT INTO `dados_anuais`(`id_da`, `aluno_id`, `escola_id`, `ano`, `tam_moletom`, `tam_camiseta`, `tam_calca`, `tam_bermuda`, `tam_calcado`, `tam_meia`, `etapa`, `turno`) VALUES (66,66,06,2020,02,02,02,02,02,02,02,"M");
INSERT INTO `dados_anuais`(`id_da`, `aluno_id`, `escola_id`, `ano`, `tam_moletom`, `tam_camiseta`, `tam_calca`, `tam_bermuda`, `tam_calcado`, `tam_meia`, `etapa`, `turno`) VALUES (67,67,07,2020,03,03,03,03,03,03,03,"M");
INSERT INTO `dados_anuais`(`id_da`, `aluno_id`, `escola_id`, `ano`, `tam_moletom`, `tam_camiseta`, `tam_calca`, `tam_bermuda`, `tam_calcado`, `tam_meia`, `etapa`, `turno`) VALUES (68,68,08,2020,04,04,04,04,04,04,04,"M");
INSERT INTO `dados_anuais`(`id_da`, `aluno_id`, `escola_id`, `ano`, `tam_moletom`, `tam_camiseta`, `tam_calca`, `tam_bermuda`, `tam_calcado`, `tam_meia`, `etapa`, `turno`) VALUES (69,69,09,2020,05,05,05,05,05,05,01,"M");
INSERT INTO `dados_anuais`(`id_da`, `aluno_id`, `escola_id`, `ano`, `tam_moletom`, `tam_camiseta`, `tam_calca`, `tam_bermuda`, `tam_calcado`, `tam_meia`, `etapa`, `turno`) VALUES (70,70,10,2020,06,06,06,06,06,06,02,"M");
INSERT INTO `dados_anuais`(`id_da`, `aluno_id`, `escola_id`, `ano`, `tam_moletom`, `tam_camiseta`, `tam_calca`, `tam_bermuda`, `tam_calcado`, `tam_meia`, `etapa`, `turno`) VALUES (71,71,11,2020,07,07,07,07,07,07,03,"M");
INSERT INTO `dados_anuais`(`id_da`, `aluno_id`, `escola_id`, `ano`, `tam_moletom`, `tam_camiseta`, `tam_calca`, `tam_bermuda`, `tam_calcado`, `tam_meia`, `etapa`, `turno`) VALUES (72,72,12,2020,08,08,08,08,08,08,04,"M");

























																																																																			
																																																																			
																																																																			
																																																																			
																																																																			
																																																																			
																																																																			
																																																																			
																																																																			
																																																																			
																																																																			
																																																																			
																																																																			
																																																																			
																																																																			
																																																																			
																																																																			
																																																																			
																																																																			
																																																																			
																																																																			
																																																																			
																																																																			
																																																																			
																																																																			